image:
  tag: 1.34.8-heroku
database:
  connector: postgres
auth:
  enabled: true # Note: The auth secret is defined in secrets.yaml

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - prisma.spotfire.spantree.net
  tls: [] # TODO: Make this work

postgresql:
  enabled: true # Attach a dedicated Postgres instance
  persistence:
    enabled: true